#############################################################################
############ Details of the function ########################################
#############################################################################

## Requirements
# numpy

## Input variables:
# 1. The path of the text file containing the full output generated by the SLiM simulation
# 2. The path where the text file containing mutations is to be stored


## What does the function do?
# Reads the full output generated by the SLiM simulation
# Identifies the positions of the section of the full SLiM output containing the details of segregating mutations in the population.
# Saves the details of segregating mutations in a new text file.


## Output
# 1. A text file of all mutations and their information ("mutations.txt")

## Currently only works for autosomes


import numpy as np

#slim_output_path = "b_Interim_files/SLiM_Outputs/Output_101000.txt"
#mutations_path = "b_Interim_files/Mutations/mutations.txt"
#all_genomes_path = "b_Interim_files/Genomes/all_genomes.txt"
#c_matrix_path = "b_Interim_files/C_Matrices/c_matrix.csv"
#sample_size=100

def extract_mutations(slim_output_path = "b_Interim_files/SLiM_Outputs/Output_101000.txt",
                      mutations_path = "b_Interim_files/Mutations/mutations_101000.txt"):

    
    #### Picking out mutations
    # Create an empty file to write the mutations in
    f_mutation = open(mutations_path, "w")

    # Create dicts that will be filled with line numbers and the corresponding text on those lines
    dict_1m = {}
    dict_2m = {}

    for i_m, line_m in enumerate(open(slim_output_path)):
        dict_1m[line_m.rstrip()] = i_m
        dict_2m[i_m] = line_m

    # Identify start and end points of the section showing mutations
    start_m = dict_1m["Mutations:"]
    end_m = dict_1m["Individuals:"]

    n_mutations = 0

    # Write headers 
    f_mutation.write("Temp_ID Permanent_ID Mutation_type Position s h Subpop Tick Number\n")
    for j_m in range(start_m + 1,end_m):
       f_mutation.write(dict_2m[j_m])
       n_mutations = n_mutations + 1

    f_mutation.close()



 
