### Make a list of all the output files generated by SLiM at fixed intervals during the simulation

list = []

# Number of generations
n = 100000

#Frequency at which outputs were generated
f = 500

for i in range(f, n+1, f):
    list = list + [f"Output_{i}.txt"]

print(list)

### Create an empty file to write the mutations in
f_mutation = open("mutations_all_gen.txt", "w")
# Write headers
f_mutation.write("Tick_Number Temp_ID Permanent_ID Mutation_type Position s h Subpop Tick Number\n")
### Loop through all the files in the list and only add the mutations, as well as the generation


for file in list:
    

    # Read the output file created by SliM
    #f_simout = open(list[file]).read()


    # Create an empty dict to identify the starting and ending positions of the portion of the output file that contains the mutaions
    dict_1 = {}
    # Create the opposite dict to generate the required output
    dict_2 = {}

    for i, line in enumerate(open(file)):
        dict_1[line.rstrip()] = i
        dict_2[i] = line

    # Identify start and end points of the section showing mutations
    start = dict_1["Mutations:"]
    end = dict_1["Individuals:"]

    generation = file.replace("Output_", "").replace(".txt", "")

    
    
    for i in range(start + 1,end):
        f_mutation.write(f"{generation} {dict_2[i]}")

f_mutation.close()



        


