## Modified from: https://tskit.dev/pyslim/docs/stable/vignette_coalescent_diversity.html


######## Python script that uses msprime and pyslim to generate a add neutral mutations to the SLiM burnin simulation ########

import pyslim
import msprime
import numpy
import sys
import tskit

################# Paths ####################

msprime_output_path = sys.argv[1]
slim_output_path = sys.argv[2]

############################################


# Read the tree sequency file generated by the nurnin SLiM simulation (i.e. "Output_history.trees")

ts = tskit.load(f"{slim_output_path}/sim{sys.argv[4]}_output_history.trees") # sys.argv[2] indicates the directory whee the SLiM history simulation stores its final output


####### Add mutations #######

# Specifies that these mutations are going to be drawn using the infinite alleles model and are going to be assigned type "m1" in SLiM

next_id = pyslim.next_slim_mutation_id(ts) # Makes the SLiM IDs of these mutations begin where they left off for the last selected mutation

neutral_mut_model = msprime.SLiMMutationModel(type=1, next_id=next_id)

ts = msprime.sim_mutations(ts, rate = float(sys.argv[3]), model = neutral_mut_model, keep = True)

print(f"The tree sequence now has {ts.num_mutations} mutations, at "
      f"{ts.num_sites} distinct sites.")



###### Correct the metadata and save ######

#ts_metadata = tables.metadata
#ts_metadata["SLiM"]["model_type"] = "WF"
#tables.metadata = ts_metadata
#ts = tables.tree_sequence()
ts.dump(f"{msprime_output_path}/sim{sys.argv[4]}_output_history_with_neutral.trees")
