
# source("/mnt/c/Users/msamant/Documents/GitHub/Va_simulations/5_History_sim/5_Analysis_script.R")

##############################################################
########## Read, process, and analyse SLiM outputs ###########
##############################################################

rm(list = ls())

########################################################################
########### paths of various scripts and functions #####################
########################################################################


### Base path and path to Vw.Rmd (file containing Jarrod's functions) (depending on the system) ###

if(Sys.info()["nodename"]%in%c("bigfoot", "bigshot", "bigbird", "bigyin", "biggar", "bigwig", "c1", "c2", "c3", "c4", "c5", "c6")){
  
  base_path = "/ceph/users/marun/Va_simulations/5_History_sim"
  Vw_path = "/ceph/users/marun/Va_simulations/6_Code_Test/Vw.Rmd"
  
}else{
  
  
  if(Sys.info()["nodename"]=="vera.bio.ed.ac.uk"){
    
    base_path = "/data/home/msamant/Manas/Va_simulations/Github/Va_simulations/5_History_sim" ## ON VERA
    Vw_path = "/data/home/msamant/Manas/Va_simulations/Github/Va_simulations/6_Code_Test/Vw.Rmd"  ### Jarrod's functions and other code is stored here
    
    
  }else{
    
    if(Sys.info()["sysname"]=="Linux"){
      
      base_path = "/mnt/c/Users/msamant/Documents/GitHub/Va_simulations/5_History_sim" ## Local Wsl
      Vw_path = "/mnt/c/Users/msamant/Documents/GitHub/Va_simulations/6_Code_test/Vw.Rmd" ### Jarrod's functions and other code is stored here
      
    }else{
      
      base_path = "C:/Users/msamant/Documents/GitHub/Va_simulations/5_History_sim" ## Local windows
      Vw_path = "C:/Users/msamant/Documents/GitHub/Va_simulations/6_Code_test/Vw.Rmd" ### Jarrod's functions and other code is stored here
      
    }
    
  }
  
  
}


# Paths to various scripts that are used for running the simulations and extracting information from SLiM outputs

msprime_burnin_path = file.path(base_path, "0_neutral_burnin.py")                                             ## msprime script generating the initial sequences
slim_history_path = file.path(base_path, "1_History.slim")                                                    ## SLiM script running the history
msprime_add_neutral_path = file.path(base_path, "1_History_add_neutral_mut.py")                               ## msprime script that adds neutral mutations to the tree sequence generated by 1_History.slim
slim_expt_path = file.path(base_path, "4_Experiment.slim")                                                    ## SLiM script running the experiment
extract_genomes_path = file.path(base_path, "3_Extract_genomes.py")                                           ## Python script extracting mutations and genomes from the SLiM output file 
extract_mut_path = file.path(base_path, "2_Extract_mutations.py")                                             ## Python script extracting mutations from the SliM output file

# Paths to various temporary directories

slim_output_path = paste(base_path, "/b_Interim_files/SLiM_outputs", sep = "")                                ## Path where SLiM and msprime output files are stored
mutations_path = paste(base_path, "/b_Interim_files/Mutations", sep = "")                                     ## Path for text file containing mutations generated by the python script  
c_matrix_path = paste(base_path, "/b_Interim_files/C_matrices", sep = "")                                     ## .csv file storing c matrix generated by the python script
output_path = paste(base_path, "/c_Output", sep = "")


####################################
######### Packages #################
####################################

library(MCMCglmm)
library(asreml)
library(Matrix)
library(rmutil)
library(pryr) ## For tracking memory usage using mem_used()
library(bigalgebra)

#################################
#### Load Jarrod's functions ####
#################################

functions_only=TRUE ## Read only the functions

rmarkdown::render(file.path(Vw_path))

##############################
### Load Manas's functions ###
##############################

rmarkdown::render(file.path(base_path, "Vw_sim_functions.Rmd"))

#### Enter the Set_ID of the simulations to be analysed ###

Set_ID = "SCE-BIO-C06645_2024-07-30_17:37:42.53745"

### Extract sim data ###

sim_data = extract_slim_data(Set_ID = Set_ID,
                             sim = 1,
                             slim_output_path = slim_output_path, 
                             sim_param_path = output_path,
                             extract_genomes_path = extract_genomes_path, 
                             extract_mut_path = extract_mut_path,
                             mutations_path = mutations_path, 
                             c_matrix_path = c_matrix_path, 
                             randomise = TRUE)
### Analyse ###

parents_info = analyse_parents(c0 = sim_data$c0,  
                               list_alpha = sim_data$list_alpha,             
                               LDdelta=FALSE,         
                               SNPs = sim_data$SNPs,                   
                               RecombRate = sim_data$sim_params$r_expt,             
                               HapLength = sim_data$sim_params$sequence_length,              
                               AtleastOneRecomb=FALSE)