## Modified from: https://tskit.dev/pyslim/docs/stable/vignette_coalescent_diversity.html


######## Python script that uses msprime and pyslim to generate a add neutral mutations to the SLiM burnin simulation ########

import pyslim
import msprime
import numpy
import sys
import tskit

################# Paths ####################

slim_output_path = sys.argv[1]

############################################


# Read the tree sequency file generated by the nurnin SLiM simulation (i.e. "Output_history.trees")

ts = tskit.load(f"{slim_output_path}/{sys.argv[3]}_sim{sys.argv[4]}_output_history.trees") # sys.argv[3] and sys.argv[4] are the Set_ID and sim

####### Add mutations #######

# Specifies that these mutations are going to be drawn using the infinite alleles model and are going to be assigned type "m1" in SLiM

next_id = pyslim.next_slim_mutation_id(ts) # Makes the SLiM IDs of these mutations begin where they left off for the last selected mutation

neutral_mut_model = msprime.SLiMMutationModel(type=1, next_id=next_id)

ts = msprime.sim_mutations(ts, rate = float(sys.argv[2]), model = neutral_mut_model, keep = True) # sys.argv[2] is the neutral mutation rate (mu_neutral)

print(f"The tree sequence now has {ts.num_mutations} mutations, at "
      f"{ts.num_sites} distinct sites.")



###### Save ######


ts.dump(f"{slim_output_path}/{sys.argv[3]}_sim{sys.argv[4]}_output_history_with_neutral.trees")
